### ISSUE TITLE
Error Spawning any objects in Rviz

### ISSUE THREAD

**Issue by LeeAClift** [andreasBihlmaier/gazebo2rviz#25]
Hi, 

I am trying to spawn some models into Rviuz ( a mixture of unit boxes and .dae models) for measurement purposes. Still, whenever I run `roslaunch gazebo2rviz gazebo2rviz.launch` with a gazebo world open, I get the following error:

`Could not resolve modelname=ground_plane to its SDF file`
`[INFO] [1646050381.564920, 64.812000]: Unable to load model: ground_plane`
`Could not resolve modelname=unit_box to its SDF file`
`[INFO] [1646050381.565921, 64.813000]: Unable to load model: unit_box`

Any advice would be beneficial, thanks!

**Comment by GradyM2M** [comment]
You can try the following command to start an empty world in GAZEBO:
`roslaunch gazebo_ros empty_world.launch `
then,
`roslaunch gazebo2rviz gazebo2rviz.launch`

**Comment by ZhaotingLi** [comment]
Hi, I meet with the same problem and found this issue was caused by the default model directory of gazebo being different from the model I used in current ros_package. 

The error is sent by the function 'from_model' defined in parse.py file in https://github.com/andreasBihlmaier/pysdf, and the directory the program searches on my PC is '‘/home/lzt/.gazebo/models/', so I copied all my model files into this directory and the problem can be solved. 

Hope this helps and maybe someone can propose a better solution.

**Comment by GradyM2M** [comment]
@ZhaotingLi  Hi, your approach is correct, and you need to pay attention to the function “catkin_ws_path".

**Comment by ZZWang21** [comment]
Hi, @GradyM2M  @ZhaotingLi , I changed the directory, try to find the sdf, but it shows errors. Should the sdf files in the models root folder, or in its own folder? what else documents are needed (for example, config, meshes?)? Thanks. 

error: "[ERROR] [1670153366.967955, 1914.173000]: bad callback: <function on_link_states_msg at 0x7f46c576f3d0>
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/walter/catkin_ws_conda/src/gazebo2rviz/scripts/gazebo2tf_node.py", line 58, in on_link_states_msg
    if link.tree_parent_joint:
AttributeError: 'NoneType' object has no attribute 'tree_parent_joint'
"

**Comment by GradyM2M** [comment]
@ZZWang21 The sdf files should be placed uniformly in the models root folder '/home/name/.gazebo/models/'
